# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: Unit tests
        run:
          npm test
  
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: Run Linter
          npx eslint ./scripts ./__tests__ --ext .js,.jsx,.ts,.tsx
  
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install stuff
        run:
          npm install
      - name: Generate docs
        run:
          npm run doc
      - uses: stefanzweifel/git-auto-commit-action@v4


